import { defineArrayMember, defineField, defineType } from 'sanity';

export const homepageSettings = defineType({
  name: 'homepageSettings', title: 'Homepage settings', type: 'document', fields: [
    defineField({ name: 'heroEyebrow', type: 'string' }), defineField({ name: 'heroTitleLineOne', type: 'string' }), defineField({ name: 'heroTitleLineTwo', type: 'string' }),
    defineField({ name: 'heroDescription', type: 'text' }), defineField({ name: 'heroImage', type: 'image', options: { hotspot: true } }),
    defineField({ name: 'heroEyebrowStyle', title: 'Hero label style', type: 'textStyle', options: { collapsible: true, collapsed: true } }),
    defineField({ name: 'heroTitleStyle', title: 'Hero title style', type: 'textStyle', options: { collapsible: true, collapsed: true } }),
    defineField({ name: 'heroDescriptionStyle', title: 'Hero description style', type: 'textStyle', options: { collapsible: true, collapsed: true } }),
    defineField({ name: 'heroPrimaryCtaLabel', title: 'Primary button text', type: 'string' }), defineField({ name: 'heroPrimaryCtaHref', title: 'Primary button link', type: 'string', description: 'Use a site path such as /project or a full URL.' }),
    defineField({ name: 'heroSecondaryCtaLabel', title: 'Secondary button text', type: 'string' }), defineField({ name: 'heroSecondaryCtaHref', title: 'Secondary button link', type: 'string', description: 'Use a site path such as /experiments or a full URL.' }),
    defineField({ name: 'startingHandicap', title: 'Starting handicap', type: 'string', description: 'The handicap at the beginning of the project. Used to calculate progress automatically.' }),
    defineField({ name: 'currentHandicap', type: 'string' }), defineField({ name: 'targetHandicap', type: 'string' }), defineField({ name: 'progressPercent', type: 'number', hidden: true, description: 'Legacy field. Progress is now calculated automatically.' }),
    defineField({ name: 'stats', type: 'array', of: [defineArrayMember({ type: 'stat' })], validation: (rule) => rule.max(4) }),
    defineField({ name: 'roadEyebrow', title: 'Road section label', type: 'string' }), defineField({ name: 'roadHeading', title: 'Road section heading', type: 'string' }), defineField({ name: 'roadDescription', title: 'Road section description', type: 'text' }),
    defineField({ name: 'sectionEyebrowStyle', title: 'Section label style', type: 'textStyle', options: { collapsible: true, collapsed: true } }),
    defineField({ name: 'sectionHeadingStyle', title: 'Section heading style', type: 'textStyle', options: { collapsible: true, collapsed: true } }),
    defineField({ name: 'sectionDescriptionStyle', title: 'Section description style', type: 'textStyle', options: { collapsible: true, collapsed: true } }),
    defineField({ name: 'experimentsEyebrow', title: 'Experiments section label', type: 'string' }), defineField({ name: 'experimentsHeading', title: 'Experiments section heading', type: 'string' }), defineField({ name: 'experimentsDescription', title: 'Experiments section description', type: 'text' }),
    defineField({ name: 'featuredExperiments', title: 'Featured experiments', type: 'array', of: [defineArrayMember({ type: 'reference', to: [{ type: 'experiment' }] })], validation: (rule) => rule.max(3) }),
    defineField({ name: 'featuredArticles', title: 'Featured articles', type: 'array', of: [defineArrayMember({ type: 'reference', to: [{ type: 'article' }] })], validation: (rule) => rule.max(3) }),
    defineField({ name: 'journalEyebrow', title: 'Journal section label', type: 'string' }), defineField({ name: 'journalHeading', title: 'Journal section heading', type: 'string' }),
    defineField({ name: 'manifestoHeading', type: 'string' }), defineField({ name: 'manifestoEmphasis', type: 'string' }), defineField({ name: 'manifestoDescription', type: 'text' }),
    defineField({ name: 'manifestoHeadingStyle', title: 'Manifesto heading style', type: 'textStyle', options: { collapsible: true, collapsed: true } }),
    defineField({ name: 'manifestoEmphasisStyle', title: 'Manifesto emphasis style', type: 'textStyle', options: { collapsible: true, collapsed: true } }),
    defineField({ name: 'manifestoDescriptionStyle', title: 'Manifesto description style', type: 'textStyle', options: { collapsible: true, collapsed: true } }),
    defineField({ name: 'newsletterHeadingLineOne', type: 'string' }), defineField({ name: 'newsletterHeadingLineTwo', type: 'string' }), defineField({ name: 'newsletterDescription', type: 'text' }),
    defineField({ name: 'newsletterEyebrowStyle', title: 'Newsletter label style', type: 'textStyle', options: { collapsible: true, collapsed: true } }),
    defineField({ name: 'newsletterHeadingStyle', title: 'Newsletter heading style', type: 'textStyle', options: { collapsible: true, collapsed: true } }),
    defineField({ name: 'newsletterDescriptionStyle', title: 'Newsletter description style', type: 'textStyle', options: { collapsible: true, collapsed: true } }),
    defineField({ name: 'seo', type: 'seo' }),
  ], preview: { prepare: () => ({ title: 'Homepage settings' }) },
});
