import { defineArrayMember, defineField, defineType } from 'sanity';
const number = (name, title) => defineField({ name, title, type: 'number' });
export const seasonData = defineType({ name: 'seasonData', title: 'Season data', type: 'document', fields: [
  defineField({ name: 'year', type: 'number', readOnly: true }), defineField({ name: 'exportedAt', type: 'datetime', readOnly: true }), defineField({ name: 'playerName', type: 'string', readOnly: true }), defineField({ name: 'homeClub', type: 'string', readOnly: true }),
  defineField({ name: 'roundCount', type: 'number', readOnly: true }), defineField({ name: 'firstRoundDate', type: 'datetime', readOnly: true }), defineField({ name: 'latestRoundDate', type: 'datetime', readOnly: true }), defineField({ name: 'latestRoundId', type: 'string', readOnly: true, hidden: true }),
  defineField({ name: 'summary', type: 'object', readOnly: true, fields: [number('averageGross','Scoring average'),number('bestGross','Best gross'),number('averagePutts','Putts per round'),number('girPercent','GIR %'),number('fairwaysHitPercent','Fairways %'),number('scramblingPercent','Scrambling %'),number('penaltiesPerRound','Penalties per round'),number('averageStableford','Stableford average')] }),
  defineField({ name: 'handicapHistory', type: 'array', readOnly: true, of: [defineArrayMember({ type: 'object', fields: [defineField({ name: 'date', type: 'datetime' }),number('handicap','Handicap')] })] }),
  defineField({ name: 'monthlyCheckpoints', type: 'array', readOnly: true, of: [defineArrayMember({ type: 'object', fields: [defineField({ name: 'month', type: 'string' }),number('roundsPlayed','Rounds'),number('averageGross','Scoring average'),number('averagePutts','Putts'),number('girPercent','GIR %'),number('fairwaysHitPercent','Fairways %'),number('scramblingPercent','Scrambling %'),number('penaltiesPerRound','Penalties')] })] }),
  defineField({ name: 'parScoring', type: 'array', readOnly: true, of: [defineArrayMember({ type: 'object', fields: [number('par','Par'),number('holesPlayed','Holes'),number('averageGross','Average gross'),number('averageToPar','Average to par')] })] }),
  defineField({ name: 'recentRounds', type: 'array', readOnly: true, of: [defineArrayMember({ type: 'object', fields: [defineField({ name: 'date', type: 'datetime' }),defineField({ name: 'courseName', type: 'string' }),number('gross','Gross'),number('toPar','To par'),number('stablefordPoints','Stableford')] })] }),
], preview: { select: { year: 'year', rounds: 'roundCount' }, prepare: ({ year, rounds }) => ({ title: `${year || ''} season`, subtitle: `${rounds || 0} rounds imported` }) } });
